CREATE TABLE IF NOT EXISTS mprops (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    propid VARCHAR(50) NOT NULL,
    propname VARCHAR(100) NOT NULL,
    x FLOAT NOT NULL,
    y FLOAT NOT NULL,
    z FLOAT NOT NULL,
    freeze TINYINT(1) NOT NULL DEFAULT 0,
    colision TINYINT(1) NOT NULL DEFAULT 1,
    heading FLOAT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
